apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalog-deployment
spec:
  selector:
    matchLabels:
      app: bookcatalog
  template:
    metadata:
      labels:
        app: bookcatalog
    spec:
      containers:
        - name: bookcatalog
          image: hfvmarques/bookcatalog:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDBSettings__Host
              value: mongodb-service
            - name: MongoDBSettings__Password
              valueFrom:
                secretKeyRef:
                  name: bookcatalog-secrets
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readynessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bookcatalog-service
spec:
  type: LoadBalancer
  selector:
    app: bookcatalog
  ports:
    - port: 80
      targetPort: 80
